/*
 * Title:        EdgeCloudSim - Idle/Active Load Generator implementation
 * 
 * Description: 
 * IdleActiveLoadGenerator implements basic load generator model where the
 * mobile devices generate task in active period and waits in idle period.
 * Task interarrival time (load generation period), Idle and active periods
 * are defined in the configuration file.
 * 
 * Licence:      GPL - http://www.gnu.org/copyleft/gpl.html
 * Copyright (c) 2017, Bogazici University, Istanbul, Turkey
 */

package edu.boun.edgecloudsim.task_generator;

import java.util.ArrayList;

import org.apache.commons.math3.distribution.ExponentialDistribution;
import org.apache.commons.math3.random.Well19937c;

import edu.boun.edgecloudsim.core.SimSettings;
import edu.boun.edgecloudsim.core.SimSettings.APP_TYPES;
import edu.boun.edgecloudsim.utils.EdgeTask;
import edu.boun.edgecloudsim.utils.SimLogger;
import edu.boun.edgecloudsim.utils.SimUtils;


/**
 * 
 * @author szs0117
 *
 */
public class IdleActiveLoadGenerator extends LoadGeneratorModel{

	
	/**
	 * 
	 * @param _numberOfMobileDevices
	 * @param _simulationTime
	 * @param _simScenario
	 */
	public IdleActiveLoadGenerator(int _numberOfMobileDevices, double _simulationTime, String _simScenario) {
		super(_numberOfMobileDevices, _simulationTime, _simScenario);
	}

	
	/**
	 * 
	 */
	@Override
	public void initializeModel() {
		taskList = new ArrayList<EdgeTask>();
		
		//exponential number generator for file input size, file output size and task length
		ExponentialDistribution[][] expRngList = new ExponentialDistribution[SimSettings.APP_TYPES.values().length][3];
		
		//create random number generator for each place
		for(int i=0; i<SimSettings.APP_TYPES.values().length; i++) {
			if(SimSettings.getInstance().getTaskLookUpTable()[i][0] ==0)
				continue;
			Well19937c rng = new Well19937c(SimSettings.getInstance().getRandomSeed());
			expRngList[i][0] = new ExponentialDistribution(rng, SimSettings.getInstance().getTaskLookUpTable()[i][5]);
			rng = new Well19937c(SimSettings.getInstance().getRandomSeed());
			expRngList[i][1] = new ExponentialDistribution(rng, SimSettings.getInstance().getTaskLookUpTable()[i][6]);
			rng = new Well19937c(SimSettings.getInstance().getRandomSeed());
			expRngList[i][2] = new ExponentialDistribution(rng, SimSettings.getInstance().getTaskLookUpTable()[i][7]);
		}
		
		//Each mobile device utilizes an app type (task type)
		for(int i=0; i<numberOfMobileDevices; i++) {
			APP_TYPES randomTaskType = null;
			double taskTypeSelector = SimUtils.getRandomDoubleNumber(0,100);
			double taskTypePercentage = 0;
			//randomTaskType = SimSettings.APP_TYPES.values()[numberOfMobileDevices % 4];
			
			for (SimSettings.APP_TYPES taskType : SimSettings.APP_TYPES.values()) {
				taskTypePercentage += SimSettings.getInstance().getTaskLookUpTable()[taskType.ordinal()][0];
				if(taskTypeSelector <= taskTypePercentage){
					randomTaskType = taskType;
					break;
				}
			}
			if(randomTaskType == null){
				SimLogger.printLine("Impossible is occured! no random task type!");
				continue;
			}
			
			double poissonMean = SimSettings.getInstance().getTaskLookUpTable()[randomTaskType.ordinal()][2];
			double activePeriod = SimSettings.getInstance().getTaskLookUpTable()[randomTaskType.ordinal()][3];
			double idlePeriod = SimSettings.getInstance().getTaskLookUpTable()[randomTaskType.ordinal()][4];
			double activePeriodStartTime = SimUtils.getRandomDoubleNumber(10, 10+activePeriod);  //start from 10th seconds
			double virtualTime = activePeriodStartTime; //start from 10th seconds

			Well19937c rng = new Well19937c(SimSettings.getInstance().getRandomSeed());
			ExponentialDistribution rngDistribution = new ExponentialDistribution(rng, poissonMean);
			while(virtualTime < simulationTime) {
				double interval = rngDistribution.sample();

				if(interval <= 0){
					SimLogger.printLine("Impossible is occured! interval is " + interval + " for device " + i + " time " + virtualTime);
					continue;
				}
				//SimLogger.printLine(virtualTime + " -> " + interval + " for device " + i + " time ");
				virtualTime += interval;
				
				if(virtualTime > activePeriodStartTime + activePeriod){
					activePeriodStartTime = activePeriodStartTime + activePeriod + idlePeriod;
					virtualTime = activePeriodStartTime;
					continue;
				}
				
				boolean sens = (SimUtils.getRandomDoubleNumber(0, 100) < 67);
				boolean act = (!sens || SimUtils.getRandomDoubleNumber(0, 100) < 50);
				boolean wifi = true;
				
				EdgeTask newTask = new EdgeTask(i, randomTaskType, virtualTime, expRngList, wifi, sens, act);
				//SimLogger.printLine("" + newTask.getMobileDeviceId());
				//Changed by Qian if this task is generated by sensor, you can uncomment code inside the if statement and set destination mobile device ID. 
				//Also uncomment codes of line 491 inside MobileDeviceManager.jave.
				if (sens) {		
					//newTask.setDesMobileDeviceId(i + numberOfMobileDevices);
					//SimLogger.printLine("Source: " + i + " Des: " + newTask.getDesMobileDeviceId());
				}
				
				taskList.add(newTask);
			}
		}
	}

}
